### PR TITLE
[Issue 71] Match notebook style: max image width and text cell overflow.

### LINKED ISSUE #71: Images do not resize to cell width
In the dashboard notebook plugin, images in cells will resize to cell width:

image

In the dashboard server, images are always full size:

image

This is using all Markdown cells with `` elements.

### PR DESCRIPTION
**Pull request by dalogsdon**
Resolves #71

### CODE REVIEW

**Comment by parente** [comment]
Can you add the sample notebook into `data/` for testing?

**Comment by parente** [comment]
Causes markdown text to get clipped unlike in notebook. Confirmed this does not happen on master.

screen shot 2016-02-09 at 10 54 36 pm

screen shot 2016-02-09 at 10 54 43 pm

**Comment by dalogsdon** [comment]
This PR is exposing more instances of issue #84. In the case of the `test_busy_indicator` dashboard, the incorrect header size is pushing the text out of the cell.

**Comment by parente** [comment]
Yes. Makes sense. Do you want to address in this PR or get this in and go tackle them in #84?

**Comment by dalogsdon** [comment]
> get this in and go tackle them in #84

**Comment by parente** [comment]
Done. Have at it.

**Pull request merged**
