### PR TITLE
[Issue 50] Use a websocket library for encode/decode

### PR DESCRIPTION
**Pull request by jhpedemonte**
This is mostly working. But getting an error when reloading the **lorenz.ipynb** notebook:

```
INFO:tornado.access:201 POST /api/kernels?1455314417980 (192.168.99.1) 12.44ms
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/ipykernel/kernelbase.py", line 175, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/opt/conda/lib/python3.4/site-packages/jupyter_client/session.py", line 845, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'ac5df653213574c1755ec9ce010e6e63d5af24362aa23d745cfa32d594bfdda6'
```

Ref #50 

---

**TODO:**
* [x] Cleanup/refactor
* [x] Error handling
* [ ] ~~Handle large messages across frames ??~~ => opened as #97
    * We didn't have support for this with our previous WS impl, either
* [x] Fix tests

### CODE REVIEW

**Comment by jhpedemonte** [comment]
Better! Seems to be working now. Just need to clean up and refactor.

**Comment by jhpedemonte** [comment]
Cleaned up code and added better error handling. Also updated the unit tests. Should hopefully go green soon.

**Comment by parente** [comment]
Seems to work locally for me. I'll get with @jtyberg to see if it also fixes #56. @dalogsdon / @jhpedemonte if you guys are happy with the code, go ahead and merge.

**Comment by parente** [comment]
Also can't see to reproduce #56 after this update in an environment where we used to hit it all the time. Let's :shipit: .

**Pull request merged**
